#WAP TO CONVERT USER INPUT NUMBER TO HOURS AND MINUTES
#EX : USER INPUT =150
#OUTPUT: 2 HOURS AND 30 MINTUES
#NAME : KRISHNADEEPSINH
#DATE : 9/1/26

no1=int(input("ENTER NUMBER :"))

hours=no1//60;
min=no1%60;
print("HOURS ARE :",hours)
print("MIN ARE :",min)
