#WAP TO CONVERT USER INPUT NUMBER TO KILOS AND GRAMS
#EX : USER INPUT =2500
#OUTPUT: 2  AND 30 MINTUES
#NAME : KRISHNADEEPSINH
#DATE : 9/1/26

no=int(input("ENTER NO :"))
kg=no//1000;
gram=no%1000;
print("KILOGRAM ARE : ",kg)
print("GRAM ARE : ",gram)